version: "3.7"
services:
  ecommerce-backend:
    container_name: ecommerce-backend
    image: ecommerce-backend:v1
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4001:4001"
    networks:
      - ecommerce-app
networks: 
  ecommerce-app:
  
  
